server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://asset-management-system-npgv.onrender.com/api/;

        proxy_ssl_server_name on;

        proxy_set_header Host asset-management-system-npgv.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass https://asset-management-system-npgv.onrender.com/admin/;

        proxy_ssl_server_name on;

        proxy_set_header Host asset-management-system-npgv.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        proxy_pass https://asset-management-system-npgv.onrender.com/static/;

        proxy_ssl_server_name on;

        proxy_set_header Host asset-management-system-npgv.onrender.com;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}